image: leapcode/ruby
before_script:
  - ruby -v
  - sudo gem install bundler --no-ri --no-rdoc
  - sudo bundle install --jobs $(nproc) --without system_tests --path=/var/cache/gitlab-runner/ "${FLAGS[@]}"

# don't fail on lint warnings
rspec:
  script:
    - bundle exec rake lint || /bin/true
    - bundle exec rake syntax
    - bundle exec rake validate
    - bundle exec rake spec
